### ISSUE TITLE
NGINX Mon Pattern Traffic Routing and NGINX resource issue

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/cdk-aws-observability-accelerator#125]
**Describe the bug**
NGINX Mon Pattern Traffic Routing and NGINX resource issue

**To Reproduce**
While working on the [NGINX Mon Pattern](https://aws-observability.github.io/cdk-aws-observability-accelerator/patterns/single-new-eks-observability-accelerators/single-new-eks-nginx-opensource-observability/) after step 5 `Deploy an example Nginx application` `Ingress` resource fails after using the below `Ingress` resource it works, documentation needs to be updated.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-demo
  namespace: {{namespace}}
spec:
  ingressClassName: nginx
  rules:
  - host: '<Complete URL of NGINX LB SERVICE>'
    http:
      paths:
        - path: /apple
          pathType: Prefix
          backend:
            service:
              name: apple-service
              port: 
                number: 5678
        - path: /banana
          pathType: Prefix
          backend:
            service:
              name: banana-service
              port: 
                number: 5678
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
